# Generated by Django 5.0.4 on 2024-04-26 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextToImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('sd_api_request', models.JSONField(blank=True, null=True)),
                ('sd_api_response', models.JSONField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Text To Image',
                'verbose_name_plural': 'Text To Images',
            },
        ),
    ]
