# Generated by Django 5.0.4 on 2024-04-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttoimage',
            name='exception',
            field=models.TextField(blank=True, null=True),
        ),
    ]
